name: ci-format-test

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run prettier
        run: pnpm format:fix

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run jest
        run: pnpm test
