name: ci-format-test

on:
  pull_request:
    branches: [main]

jobs:
  romeTools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm rome:apply && pnpm rome:write

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: "pnpm"

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm test
