name: Jest Test

on: 
  pull_request:
    branches: [ main ]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    
    - name: Use Nodejs
      uses: actions/setup-node@v3.5.1
      with:
        node-version: '16.x'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: latest
        run_install: false
        
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    - name: install dependencies
      run: pnpm install
      
    - name: Run Jest
      run: pnpm test
