name: Jest Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches: main

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Run Jest
        run: |
          pnpm install
          pnpm run test
